### DISCUSSION TITLE
configuration issue

### DISCUSSION THREAD

**Discussion by JunseoChoJJ** [projectnessie/nessie#8701] [Q&A] [answered]
try to deploy nessie + spark + iceberg + s3a on k8s envirnoment

working on nessie with postgresql but getting this error 

pod/nessie-6f86d47f77-dxv4j   0/1     CrashLoopBackOff   10 (54s ago)   28m

WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.rest.gzip.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
  [org.pro.ser.con.ConfigChecks] (main) Both authentication (AuthN) and authorization (AuthZ) are disabled, all requests to Nessie will be permitted. This means: everybody with access to Nessie can read, write and change everything. Recommended action: Enable AuthN & AuthZ, see https://projectnessie.org/try/configuration/
[org.pro.qua.pro.sto.JdbcBackendBuilder] (main) Selected datasource: postgresql
 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: java.sql.SQLException: Acquisition timeout while waiting for new connection

nessie-postgresql.yaml file
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: nessie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: nessie_catalog
            - name: POSTGRES_USER
              value: postgres_user
            - name: POSTGRES_PASSWORD
              value: postgres_password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: nessie
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001  # Choose a suitable nodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-creds
  namespace: nessie
type: Opaque
data:
  username: 'base64'
  password: 'base64'
```

postgres-creds
```
POSTGRESQL_USERNAME=postgres_user
POSTGRESQL_PASSWORD=postgres_password

```
values.yaml for helm chart

```
versionStoreType: JDBC
jdbc:  
  jdbcUrl: jdbc:postgresql://postgres-service:30001/nessie
  secret:
    name: postgres-creds
    username: POSTGRESQL_USERNAME
    password: POSTGRESQL_PASSWORD

```
