### ISSUE TITLE
[Bug]: Helm Chart Installation Fails with "incompatible types for comparison" Error

### ISSUE THREAD

**Issue by jordi-ydteam** [projectnessie/nessie#10864]
## Summary

The Nessie Helm chart installation fails when configuring S3 storage options in `values.yaml` with the error: `error calling ne: incompatible types for comparison`. This occurs in the `nessie.addConfigOption` and `nessie.appendConfigOption` helper functions when they attempt to compare certain YAML values with `nil`.

## Environment

- **Helm Version**: 3.x
- **Kubernetes Version**: Any
- **Nessie Chart Version**: Latest (from `nessie-helm-0.104.1.tgz`)
- **Operating System**: macOS (likely affects all platforms)

## Steps to Reproduce

1. Create a `values.yaml` file with S3 configuration:
   ```yaml
   catalog:
     enabled: true
     iceberg:
       defaultWarehouse: warehouse
       warehouses:
       - name: warehouse
         location: s3://my-bucket/
     storage:
       s3:
         defaultOptions:
           region: "value"  # This specific value triggers the issue
           endpoint: "https://value.provider.com"
           pathStyleAccess: true
           authType: STATIC
           accessKeySecret:
             name: "nessie-s3-credentials"
             awsAccessKeyId: "access-key-id"
             awsSecretAccessKey: "secret-access-key"
   ```

2. Attempt to install or template the chart:
   ```bash
   helm template nessie-test ./nessie --values values.yaml --namespace nessie
   ```

## Expected Behavior

The Helm chart should successfully render templates and allow installation with the provided S3 configuration.

## Actual Behavior

The command fails with the following error:

```
Error: template: nessie/templates/deployment.yaml:41:46: executing "nessie/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: nessie/templates/configmap.yaml:204:107: executing "nessie/templates/configmap.yaml" at <include "nessie.applyCatalogStorageS3BucketOptions">: error calling include: template: nessie/templates/_helpers.tpl:175:4: executing "nessie.applyCatalogStorageS3BucketOptions" at <include "nessie.addConfigOption" (list .region $map (print $prefix "region"))>: error calling include: template: nessie/templates/_helpers.tpl:401:8: executing "nessie.addConfigOption" at <ne $value nil>: error calling ne: incompatible types for comparison
```

## Root Cause

The issue occurs in two helper functions in `helm/nessie/templates/_helpers.tpl`:

1. **`nessie.addConfigOption`** (around line 401)
2. **`nessie.appendConfigOption`** (around line 417)

Both functions use the Helm/Sprig `ne` (not equal) function to compare values with `nil`:

```yaml
{{- if (ne $value nil) -}}
```

When certain YAML values are processed by Helm's template engine, they can be interpreted as data types that are incompatible with the `ne` comparison function. This particularly affects string values that may be parsed as special types (block scalars, multi-line strings, etc.).

## Proposed Solution

Replace the problematic `ne $value nil` comparisons with simpler `if $value` checks:

### File: `helm/nessie/templates/_helpers.tpl`

**Change 1 - In `nessie.addConfigOption` function (around line 401):**
```yaml
# Current (problematic):
{{- if (ne $value nil) -}}

# Proposed fix:
{{- if $value -}}
```

**Change 2 - In `nessie.appendConfigOption` function (around line 417):**
```yaml
# Current (problematic):
{{- if ne $value nil -}}

# Proposed fix:
{{- if $value -}}
```

### Rationale for the Fix

- `{{- if $value -}}` is more robust and type-agnostic
- It evaluates to `true` for any non-empty, non-nil, non-false, non-zero value
- It avoids the type comparison that causes the error
- It maintains the same logical behavior: only process configuration options that have actual values
- This approach is commonly used in Helm templates to avoid type-related issues

## Additional Context

- The error appears to be triggered by specific string values (like `"nbg1"`) but the exact conditions that cause certain strings to be interpreted as incompatible types are unclear
- The issue affects S3 configuration but likely impacts other storage providers as well
- This is a Helm template engine issue rather than a Nessie application issue
- The proposed fix is backward compatible and should not affect existing functionality

## Workaround

Currently, there is no known workaround other than modifying the helper functions as described above.

## Impact

This bug prevents users from installing the Nessie Helm chart with custom S3 storage configurations, which is a common use case for production deployments.

---

**Note**: This issue was discovered and analyzed through extensive debugging of the Helm template rendering process. The proposed solution has been tested and resolves the installation failure while maintaining functional equivalence.

### How to reproduce it

# How to Reproduce the Helm Chart Installation Error

## Prerequisites
- Helm 3.x installed
- Access to a Kubernetes cluster (local or remote)
- Nessie Helm chart available locally or via repository

### 1. Download/Access Nessie Helm Chart
```bash
# Option A: If using Helm repository
helm repo add nessie https://charts.projectnessie.org
helm repo update

# Option B: If using local chart
git clone https://github.com/projectnessie/nessie.git
cd nessie/helm
```

### 2. Create a values.yaml file with S3 configuration
Create a file named `values-reproduction.yaml` with the following content:

```yaml
catalog:
  enabled: true
  iceberg:
    defaultWarehouse: warehouse
    configDefaults: {}
    configOverrides: {}
    warehouses:
    - name: warehouse
      location: s3://test-bucket/
      configDefaults: {}
      configOverrides: {}
    objectStoresHealthCheckEnabled: true

  storage:
    retryAfter: ~
    s3:
      defaultOptions:
        region: "nbg1"  # This specific value triggers the issue
        endpoint: "https://value.provider.com"
        externalEndpoint: ~
        pathStyleAccess: true
        accessPoint: ~
        allowCrossRegionAccessPoint: ~
        authType: STATIC
        requestSigningEnabled: ~
        stsEndpoint: ~
        accessKeySecret:
          name: "nessie-s3-credentials"
          awsAccessKeyId: "access-key-id"
          awsSecretAccessKey: "secret-access-key"
        clientIam:
          enabled: ~
          roleArn: ~
          policy: ~
          roleSessionName: ~
          externalId: ~
          sessionDuration: ~
          statements: ~
        serverIam:
          enabled: ~
          roleArn: ~
          policy: ~
          roleSessionName: ~
          externalId: ~
          sessionDuration: ~
      buckets: []
      transport:
        maxHttpConnections: ~
        readTimeout: ~
        connectTimeout: ~
        connectionAcquisitionTimeout: ~
        connectionMaxIdleTime: ~
        connectionTimeToLive: ~
        expectContinueEnabled: ~
      sessionCredentials:
        sessionCredentialRefreshGracePeriod: ~
        sessionCredentialCacheMaxEntries: ~
        stsClientsCacheMaxEntries: ~
```

### 3. Attempt to render the Helm template
```bash
# If using repository chart:
helm template nessie-test nessie/nessie --values values-reproduction.yaml --namespace nessie --debug

# If using local chart:
helm template nessie-test ./nessie --values values-reproduction.yaml --namespace nessie --debug
```

### 4. Observe the error
The command will fail with the error:
```
Error: template: nessie/templates/deployment.yaml:41:46: executing "nessie/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: nessie/templates/configmap.yaml:204:107: executing "nessie/templates/configmap.yaml" at <include "nessie.applyCatalogStorageS3BucketOptions">: error calling include: template: nessie/templates/_helpers.tpl:175:4: executing "nessie.applyCatalogStorageS3BucketOptions" at <include "nessie.addConfigOption" (list .region $map (print $prefix "region"))>: error calling include: template: nessie/templates/_helpers.tpl:401:8: executing "nessie.addConfigOption" at <ne $value nil>: error calling ne: incompatible types for comparison
```

### 1. Create minimal values.yaml
```yaml
catalog:
  enabled: true
  iceberg:
    defaultWarehouse: warehouse
    warehouses:
    - name: warehouse
      location: s3://test-bucket/
  storage:
    s3:
      defaultOptions:
        region: "nbg1"
```

### 2. Run the same helm template command
The error will occur at the same location, confirming that the issue is specifically with the `region: "nbg1"` value processing in the Helm template.

## Notes
- The error is consistent across different Helm versions (tested on 3.12+)
- The issue appears to be related to how specific string values are processed by Helm's template engine
- Other region values (like "us-east-1") may or may not trigger the same issue
- The error occurs during template rendering, before any actual Kubernetes resources are created 

### Nessie server type (docker/uber-jar/built from source) and version

docker (via Helm chart nessie-helm-0.104.1.tgz) - Issue occurs during template rendering, before server deployment
