### ISSUE TITLE
[Bug]: Failure getting s3 creds from secret (Helm)

### ISSUE THREAD

**Issue by wlfgang** [projectnessie/nessie#10987]
### What happened

Something appears to have changed between 0.104.1 and 0.104.2. I deploy nessie using the helm chart, specifying s3 credentials in a Kubernetes Secret, which I reference in my values.yaml.

In the log, I first see:
```
DEBUG [io.sma.config] (executor-thread-2) SRCFG01002: The config nessie-catalog-secrets.s3.default-options.access-key was not found
```

Then later:
```
ERROR [org.pro.ser.cat.ObjectStoresHealthCheck] (executor-thread-1) Failed to ping warehouse 'warehouse', error ID ae46bcfb-48f5-4fdd-82c3-ce52cad068cf: java.lang.IllegalArgumentException: Missing access key and secret for STATIC authentication mode
```

The server fails to come up due to this error.

Inside the pod I can see the environment variables are set, and have correct values:
```
nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:nessie-catalog-secrets.s3.default-options.access-key
nessie-catalog-secrets.s3.default-options.access-key.name=xxxxx
nessie-catalog-secrets.s3.default-options.access-key.secret=xxxxx
```

Again this all works fine on 0.104.1 and earlier.

### How to reproduce it

In values.yaml, I have:
```
image:
  tag: "0.104.2"
    s3:
      defaultOptions:
        accessKeySecret: 
          name: s3creds
          awsAccessKeyId: accessKeyId
          awsSecretAccessKey: accessKey
```
I create the secret like:
```
kubectl create secret generic s3creds \
  --from-literal=accessKeyId=<access-key-id> \
  --from-literal=accessKey=<access-key> \
  -n nessie
```
I do a `helm upgrade`, then get the errors in the pod's logs.

### Nessie server type (docker/uber-jar/built from source) and version

Standard container image, 0.104.2
