### ISSUE TITLE
[Helm chart] Add PVC for ROCKSDB path

### ISSUE THREAD

**Issue by julwin** [projectnessie/nessie#5937]
**Description**:
When deploying Nessie using the helm chart with ROCKSDB enabled, there is no way to use a path on a PVC. Thus, on every restart of the deployment, the data is lost. 

To allow this with the helm chart, a PVC could be added to the template that is mounted and used as storage location for ROCKSDB.

**Requested Changes in public API**:
- Changes in Helm chart

**Expected Use Cases**:
Persisting data in kubernetes environments.

**Comment by dimas-b** [comment]
@julwin : Please have a look at #5952 . Does it help with your use case?

**Comment by julwin** [comment]
@dimas-b It's not only helping, it solves it 😁 

PR looks like a great addition to me, I'll gladly assist in testing if you'd like to. 

This makes Nessie more or less a "standalone-deployment" 👍

**Comment by dimas-b** [comment]
@julwin : If you could validate the PR before it is merged, it'd be great. Otherwise, we'll try and do a patch release to publish the updated helm chart soon.

**Comment by julwin** [comment]
@dimas-b Alright, I tested it. Got the following error at first:

`failed to provision volume with StorageClass "cinder": claim Selector is not supported` - VolumeClaim not provisioned.

I then modified the `storage.yaml` and added the `storageClassName` key:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-nessie
  labels:
    helm.sh/chart: nessie-0.47.1
    app.kubernetes.io/name: nessie
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.47.1"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder
```

This now works without an error, so I would suggest adding the storageClassName key to the helm chart ([e.g. airflow does it the same way](https://github.com/apache/airflow/blob/main/chart/templates/dags-persistent-volume-claim.yaml))

As further addition, it might be a good idea to include the storage Size as well, to make it configurable, something like this:

```yaml
# this is needed when selecting ROCKS
rocksdb:
  dbPath: /rocks-nessie
  size: 5Gi
  storageClassName: cinder
```
