### ISSUE TITLE
Rethink telemetry support in Helm chart

### ISSUE THREAD

**Issue by adutra** [projectnessie/nessie#6105]
Currently the Helm chart exposes the following values:

```yaml
jaegerTracing:
  # -- Specifies whether jaeger tracing for the nessie server should be enabled.
  enabled: false
  # -- The traces endpoint, in case the client should connect directly to the Collector, e.g. http://jaeger-collector:14268/api/traces
  endpoint: ""
  # -- The Jaeger service name.
  serviceName: nessie
  # -- Whether metrics are published if tracing is enabled.
  publishMetrics: true
  # -- The sampler type (const, probabilistic, ratelimiting or remote).
  samplerType: ratelimiting
  # -- The request sampling probability. 1=Sample all requests. Set samplerParam to somewhere between 0 and 1, e.g. 0.50, if you do not wish to sample all requests.
  samplerParam: 1
```

But these settings date back to pre-Open Telemetry times, and might not even function properly anymore.
