### ISSUE TITLE
Invalid boolean attribute names in Nessie Open API spec

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#6675]
For example:
```
    Merge1:
      title: Merge Operation
      required:
      - fromRefName
      - fromHash
      type: object
      properties:
[...]
        dryRun:
          description: |
            When set to 'true' instructs the server to validate the request but to avoid committing any changes.
          type: boolean
```
However, the real JSON has: `"isDryRun"`, cf. https://github.com/projectnessie/nessie/blob/main/api/model/src/test/java/org/projectnessie/api/v2/params/TestParamObjectsSerialization.java
