### ISSUE TITLE
Ingress configuration not working when path is not root ("/")

### ISSUE THREAD

**Issue by julwin** [projectnessie/nessie#6836]
**What happened**:

I am configuring nessie ingress like this using the helm chart:

```
ingress:
  enabled: true
  annotations:
    {
      "cert-manager.io/cluster-issuer": "my-acme",
      "traefik.ingress.kubernetes.io/router.middlewares": "nessie-nessie-mw@kubernetescrd",
    }
  hosts:
    [
      {
        "host": "my.domain.net",
        "paths": ["/nessie"],
      },
    ]
  tls:
    - hosts:
        - my.domain.net
      secretName: my.domain.net
```

Middleware:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nessie-mw
  namespace: nessie
spec:
  stripPrefix:
    prefixes:
      - /nessie
    forceSlash: false
```

Instead of showing the nessie frontend, I only get blank pages.

**What you expected to happen**:

Nessie being available on my domain at /nessie

**How to reproduce it (as minimally and precisely as possible)**:
Configure nessie ingress to use non-root paths.

**Details**:
- Nessie server type (docker/built from source) and version:
- Client type (Ex: UI/Spark/pynessie ...) and version:
