### ISSUE TITLE
Improve SecretsManager API for easier configuration

### ISSUE THREAD

**Issue by adutra** [projectnessie/nessie#9485]
### Issue description

I wonder if it's possible to change the `SecretsManager` API a bit to make the secret configuration experience more user-friendly.

Here's an example of env vars for an ADLS account name + secret:

```yaml
- name: "nessie.catalog.service.adls.file-systems.filesystem1.account"
  value: "urn:nessie-secret:quarkus:nessie-catalog-secrets.adls.file-systems.filesystem1.account"
  
- name: "nessie-catalog-secrets.adls.file-systems.filesystem1.account.name"
  valueFrom:
    secretKeyRef:
      name: "adls-account-secret"
      key: "accountName"

- name: "nessie-catalog-secrets.adls.file-systems.filesystem1.account.secret"
  valueFrom:
    secretKeyRef:
      name: "adls-account-secret"
      key: "accountKeyRef"
```

That's verbose, but I'm OK with that. But when we add caching + secret reloading on top of that (see #8707), I guess we'd need to get rid of mounting secrets that way, and instead we'd get something like this:

```yaml
- name: "nessie.catalog.service.adls.file-systems.filesystem1.account"
  value: "urn:nessie-secret:k8s:adls-account-secret?name=accountName&secret=accountKeyRef"
```

While this is way more concise, it's also a bit more opaque to the user, since 2 options were grouped together. In fact the grouping is rather for technical reasons: it's done merely to facilitate secret reloading and avoid broken rotated credentials. 

If instead we can do the reloading at `SecretsManager` level, maybe we can keep the user-facing env vars more intuitive, and still achieve caching + reloading:

```yaml
- name: "nessie.catalog.service.adls.file-systems.filesystem1.account-name"
  value: "urn:nessie-secret:k8s:adls-account-secret:accountName"

- name: "nessie.catalog.service.adls.file-systems.filesystem1.account-key"
  value: "urn:nessie-secret:k8s:adls-account-secret:accountKeyRef"
```

In the above example, two keys come from the same secret `adls-account-secret`; the secret would be
fetched only once and cached. When the cache expires the secret is fetched again and all the keys
are updated together.

_In this design each `URI` in the configuration points to exactly one value_. The fact that some values might be declared in the same container (like a K8s Secret) becomes an implementation detail. This could also simplify the `Secret` hierarchy as the application doesn't need to know if a secret is a `TokenSecret` or a `BasicCredentials` etc.
