### ISSUE TITLE
[Feature]: Helm — Independently configure container and service ports

### ISSUE THREAD

**Issue by EternalDeiwos** [projectnessie/nessie#9997]
### Description

I find the template for configuring Nessie's ports odd since there is all this logic going into checking the ports between the service and deployment are synchronized when they don't have to be.

Its best practice to not bind privileged ports inside containers and expose them on whatever port after the fact; doing so will also simplify the helm templates and make them easier to maintain.

https://github.com/projectnessie/nessie/blob/9954c6eb72b86d46cb9f20d6a4b6ee534b55a09e/helm/nessie/templates/_helpers.tpl#L428-L468

### Expected Use Cases

I would like to expose Nessie from my service on ports 80/443 respectively but still have the container bind on whatever is the defaults e.g. 19120/19121.

### Requested Changes in public API

N/A

**Comment by adutra** [comment]
Your suggestion makes totally sense. I guess that the only reason why we don't have it is because it has never been asked before :-)

I would suggest something like this:

```yaml
service:
  ports:
    - name: nessie-http
      port: 80
      targetPort: 19120
    - name: nessie-https
      port: 443
      targetPort: 19121

managementService:
  port:
    name: nessie-mgmt
    port: 9000
    targetPort: 9000

extraServices:
  ports:
    - name: nessie-http-headless
      port: 19120
      targetPort: 19120
      clusterIP: None
```

It's not a difficult change per se, but we need to account for old fields (`service.ports[0].number` or `managementService.portNumber` for instance), so that users can upgrade smoothly.

WDYT?

**Comment by EternalDeiwos** [comment]
Supporting migration is necessary; even if it makes things more complicated now, it will allow the older fields to be deprecated and removed for an overall cleaner solution later.

Regarding your suggestion for `extraServices`, I'd advise mirroring the structure of a service; so you'd have this instead:

```yaml
extraServices:
  - name: nessie-http-headless
    clusterIP: None
    ports:
      - port: 19120
        targetPort: 19120
```

Similarly, `managementService` should also use the same API (i.e. [`ports: ServicePort[]`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#serviceport-v1-core)) even if only one port is defined. This will make your service definitions cleaner and more predictable.
